vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
vim.keymap.set("n", "<leader>q", vim.diagnostic.setloclist, { desc = "Open diagnostic [Q]uickfix list" })
vim.keymap.set("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "Exit terminal mode" })

vim.keymap.set("n", "<C-h>", "<C-w><C-h>", { desc = "Move focus to the left window" })
vim.keymap.set("n", "<C-l>", "<C-w><C-l>", { desc = "Move focus to the right window" })
vim.keymap.set("n", "<C-j>", "<C-w><C-j>", { desc = "Move focus to the lower window" })
vim.keymap.set("n", "<C-k>", "<C-w><C-k>", { desc = "Move focus to the upper window" })

vim.keymap.set("n", "<C-S-h>", "<C-w>H", { desc = "Move window to the left" })
vim.keymap.set("n", "<C-S-l>", "<C-w>L", { desc = "Move window to the right" })
vim.keymap.set("n", "<C-S-j>", "<C-w>J", { desc = "Move window to the lower" })
vim.keymap.set("n", "<C-S-k>", "<C-w>K", { desc = "Move window to the upper" })

vim.keymap.set("n", "<leader>e", "<cmd>Neotree toggle<cr>", { desc = "Explorer toggle" })
vim.keymap.set("n", "<leader>a", "<cmd>Alpha<cr>", { desc = "Alpha dashboard" })
vim.keymap.set("n", "<leader>o", "<cmd>Neotree focus<cr>", { desc = "Explorer focus" })
vim.keymap.set("n", "<leader>be", "<cmd>Neotree buffers toggle right<cr>", { desc = "Buffer explorer" })
vim.keymap.set("n", "<leader>ge", "<cmd>Neotree git_status toggle right<cr>", { desc = "Git explorer" })
vim.keymap.set("n", "<leader>h", function()
  require("neo-tree.command").execute({ toggle_hidden = true })
end, { desc = "Toggle hidden files" })

vim.keymap.set("n", "<C-Right>", function()
  vim.cmd("vertical resize +5")
end, { desc = "Resize → wider" })
vim.keymap.set("n", "<C-Left>", function()
  vim.cmd("vertical resize -5")
end, { desc = "Resize → narrower" })
vim.keymap.set("n", "<C-Up>", function()
  vim.cmd("resize +5")
end, { desc = "Resize ↑ taller" })
vim.keymap.set("n", "<C-Down>", function()
  vim.cmd("resize -5")
end, { desc = "Resize ↓ shorter" })
