require("plugins.hooks")
vim.pack.add(require("plugins.specs"))

require("plugins.setup.colorscheme")
require("plugins.setup.alpha")
require("plugins.setup.guess_indent")
require("plugins.setup.gitsigns")
require("plugins.setup.which_key")
require("plugins.setup.telescope")
require("plugins.setup.lsp")
require("plugins.setup.lint")
require("plugins.setup.conform")
require("plugins.setup.blink")
require("plugins.setup.treesitter")
require("plugins.setup.treesitter-textobjects")
require("plugins.setup.web_devicons")
require("plugins.setup.neotree")
require("plugins.setup.neotree").ensure()
require("plugins.setup.laravel")

vim.api.nvim_create_autocmd("VimEnter", {
  group = vim.api.nvim_create_augroup("user-deferred-plugin-setup", { clear = true }),
  once = true,
  callback = function()
    vim.schedule(function()
      require("plugins.setup.todo_comments")
      require("plugins.setup.mini")
      require("plugins.setup.lualine")
      require("plugins.setup.autopairs")
      require("plugins.setup.neoscroll")
      require("plugins.setup.harpoon")
      require("plugins.setup.tabout")
    end)
  end,
})
