require("plugins.hooks")
vim.pack.add(require("plugins.specs"))

require("plugins.setup.colorscheme")
require("plugins.setup.guess_indent")
require("plugins.setup.gitsigns")
require("plugins.setup.which_key")
require("plugins.setup.telescope")
require("plugins.setup.lsp")
require("plugins.setup.conform")
require("plugins.setup.blink")
require("plugins.setup.todo_comments")
require("plugins.setup.mini")
require("plugins.setup.treesitter")
require("plugins.setup.web_devicons")
require("plugins.setup.neotree")
require("plugins.setup.laravel")
require("plugins.setup.autopairs")
